### ISSUE TITLE
I get the following error python experiment.py --out_dir run_0

### ISSUE THREAD

**Issue by callor** [SakanaAI/AI-Scientist#81]
`$ python experiment.py --out_dir run_0
tokens per iteration will be: 16,384
C:\ProgramData\anaconda3\envs\ai_scientist\Lib\site-packages\torch\amp\autocast_mode.py:250: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(
found vocab_size = 65 (inside ../../data\shakespeare_char\meta.pkl)
Initializing a new model from scratch
number of parameters: 10.65M
Traceback (most recent call last):
  File "C:\Users\callor\Documents\workspace\Callor-sakana.ai-2024\AI-Scientist\templates\nanoGPT\experiment.py", line 697, in <module>
    final_info, train_info, val_info = train(dataset, out_dir, seed_offset)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\callor\Documents\workspace\Callor-sakana.ai-2024\AI-Scientist\templates\nanoGPT\experiment.py", line 459, in train
    model.to(device)
  File "C:\ProgramData\anaconda3\envs\ai_scientist\Lib\site-packages\torch\nn\modules\module.py", line 1173, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\ai_scientist\Lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "C:\ProgramData\anaconda3\envs\ai_scientist\Lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "C:\ProgramData\anaconda3\envs\ai_scientist\Lib\site-packages\torch\nn\modules\module.py", line 804, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\ai_scientist\Lib\site-packages\torch\nn\modules\module.py", line 1159, in convert
    return t.to(
           ^^^^^
  File "C:\ProgramData\anaconda3\envs\ai_scientist\Lib\site-packages\torch\cuda\__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
(ai_scientist)`

**Comment by Remixa-python** [comment]
You may need to have a computer card that supports a more advanced version of cuda and a corresponding cuda environment.

**Comment by kamatchu** [comment]
you must have nvidia gpu and you must try to install pytorch with cuda enabled , see installation instructions in official web site
