### ISSUE TITLE
RuntimeError: probability tensor contains either inf, nan or element < 0

### ISSUE THREAD

**Issue by AnPassingTeen** [SakanaAI/AI-Scientist#90]
Total train time: 5.93 mins
Loading meta from ../../data/shakespeare_char/meta.pkl...
Traceback (most recent call last):
  File "/root/AI-Scientist/templates/nanoGPT_lite/experiment.py", line 693, in <module>
    final_info, train_info, val_info = train(dataset, out_dir, seed_offset)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/AI-Scientist/templates/nanoGPT_lite/experiment.py", line 641, in train
    y = model.generate(
        ^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/ai_scientist/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/AI-Scientist/templates/nanoGPT_lite/experiment.py", line 308, in generate
    idx_next = torch.multinomial(probs, num_samples=1)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by conglu1997** [comment]
Fixed with https://github.com/SakanaAI/AI-Scientist/commit/d69fa1ebe22423e3cb551527f9412404ead11ad5
